### PR TITLE
[MVERIFIER-38] Define encoding for FileReader

### PR DESCRIPTION
**Pull request by KroArtem**
After discussions in https://github.com/apache/maven-verifier-plugin/pull/1 and in mailing list, I've looked at `maven-its` project and `modello` and it's not clear how to replace this plugin there. Thus I've decided to fix this small issue, update dependencies and (probably?) ask for a release.

After that this plugin can be retired. @slachiewicz , WDYT?

If you provide any ideas how to replace usages in repos mentioned above, I can do this as well. (Currently I just don't have enough knowledge about existing tools)

### CODE REVIEW

**Comment by KroArtem** [comment]
@slachiewicz, ping

**Comment by KroArtem** [comment]
@slachiewicz, ping again 😃

**Comment by slachiewicz** [comment]
Thx for reminder - please look for discussion on maven-dev mailing list

**Comment by michael-o** [comment]
Why not use source encoding defined in the POM?

**Comment by KroArtem** [comment]
@slachiewicz , there was no reaction except yours. As I have wrote in this PR, this plugin is used in two places and it is not clear how to replace it there. That's why I decided it's a good idea to fix these issues, release a new version and retire plugin.

**Comment by KroArtem** [comment]
@michael-o , I've missed your comment back then :(

I've also defined encoding in pom.xml but we also discussed FileReader here: https://github.com/apache/maven-verifier-plugin/pull/1#discussion_r365546471

I still think a new version could be released, then call plugin retired and then create issues to replace this plugin from `maven-its` project and `modello`.

@slachiewicz, wdyt?

**Pull request closed without merging**
